# Generated by Django 4.1 on 2022-09-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensajes', '0002_mensajes_rename_nombre_mensajesenviados_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='mensaje',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mensajesenviados',
            name='mensaje',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mensajesrecibidos',
            name='mensaje',
            field=models.CharField(max_length=1000),
        ),
    ]
