# Generated by Django 4.1 on 2022-09-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensajes', '0003_alter_mensajes_mensaje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajes',
            name='mensaje',
        ),
        migrations.AddField(
            model_name='mensajes',
            name='mensajes',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
