# Generated by Django 4.1 on 2022-09-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensajes', '0004_remove_mensajes_mensaje_mensajes_mensajes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajes',
            old_name='mensajes',
            new_name='texto',
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='usuario',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
